player setVariable["jk_var_side", str(playerside), true];
player addEventhandler["Respawn",{ if !(player getVariable ["BIS_revive_incapacitated",true]) then {player setVariable["jk_var_side", str(playerside), true];};}];
JK_ChangeLog = call compile preprocessfilelinenumbers "Changelog.txt";
_info = player createDiarySubject ["Info", "Info"];
player createDiaryRecord ["Info",["Credits","Logistic System - By joko // Jonas<br/>Medical Drag and Drop - By joko // Jonas<br/>TvT Template - By Joko<br/>Generell Template Rework - By Joko // Jonas<br/>Belbo - Gear Script<br/>NetFusion - AME Nametags and AME Drag and Drop<br/>Astavinu - Basic Setup and Some Functions<br/>Pychobastard - TK Protection<br/>TAW_VD<br/>Xeno - X_Reload<br/>[FHQ] Varanon - FHQ Task Tracker<br/>Vehicle Crew List By X39"]];
player createDiaryRecord ["Info",["Version",format["<font size='18'>Version 1.9 Changelog:</font><br/><br/> %1",JK_ChangeLog]]];
player createDiaryRecord ["Info",["Teamspeak der GeCo","<font size='18'Teamspeak IP:<br/>81.169.153.237:9985</font>"]];
JK_GeCo_Info = "Du hast dir Arma 2, ArmA 3 oder ein Addon aus der Reihe gekauft?<br/><br/>Dafür schon einmal „Herzlichen Glückwunsch“, denn Du hast Dir eines der umfangreichsten und vielseitigsten Spiel gekauft, dass der Softwaremarkt zurzeit her gibt! Das glaubst du nicht, dann lass Dich davon überzeugen…<br/>Arma 2 hat nun schon einige Jahre auf dem Buckel und die Zahl der Spieler nimmt nicht mehr stetig zu. Leider wird es in letzter Zeit immer schwieriger, öffentliche und gut besuchte Game-Server zu finden, die interessante COOP-Missionen und teamwork-orientiertes Gameplay bieten. Gerade diejenigen Spieler, die keinem Clan oder Squad angeschlossen sind, haben häufig nur noch die Wahl zwischen Domination, Warfare und leeren Servern. Wirkliches Teamplay – und damit die Stärke von Arma 2 / 3 - kommt leider selten auf. Nicht wenige werfen deswegen Arma 2 bzw. 3 nach kurzer Zeit wieder in die Ecke.<br/>Das Projekt GeCo möchte allen deutschsprachigen Arma 2 bzw. 3 - Neulingen, Gelegenheitsspielern - und natürlich auch allen anderen - wenigstens an ein oder zwei Tagen in der Woche eine regelmäßige Alternative bieten:<br/>    Spannende und ständig wechselnde COOP-Missionen<br/>    20+ Spieler<br/>    Teamwork<br/>    Keine Registrierungen/Anmeldungen/Reservierung/Anwesenheitspflicht<br/>    Teamspeak 3 (TS) wird zur Sprachkommunikation benutzt<br/>    (...mehr unter ""Was ist GeCo?"")<br/><br/>Die GeCo will folgende Prinzipien leben:<br/>    Teamwork<br/>    Fairness<br/>    Freundlichkeit<br/>    Hilfsbereitschaft<br/><br/>Grade wenn Du ein ""Arma2-Neuling"" bzw. ""Arma3-Neuling"" bist und nicht viel Erfahrung mit Arma 2 bzw. 3 online hast, brauchst Du keine Angst zu haben! Denn für Dich ist die GeCo erschaffen worden und wir wollen Dir zeigen, dass ArmA 2 bzw. 3 mehr als Frust ist. Mit Teamgeist, Hilfe und interessanten Missionen wollen wir Dir die aufregende, spannende und fesselnde Seite an Arma 2 bzw. 3 zeigen!<br/><br/>Mehr Informationen Findest du auf unserer Webseite ""http://mini.sixbitunder.com/geco/""";
player createDiaryRecord ["Info",["Informationen zur GeCo",JK_GeCo_Info]];
0 spawn {
    waitUntil {player == player && time > 1};
    [player] call JK_loadOut_fnc_loadOutsInit;
	[format["<img size= '6' shadow='false' image='data\geco_logo.paa'/><br/><t size='.9' color='#FFFFFF'>%1<br/></t><t size='.5' color='#FFFFFF'>%2 81.169.153.237:9985</t>", localize "STR_GECO_WELCOME_MESSAGE_1", localize "STR_GECO_WELCOME_MESSAGE_2"],0,0,2,2] spawn BIS_fnc_dynamicText;
};